// This is a Javascript test harness that simulates the execution of Lambda function code
// From the command prompt, type "node test.js"

// assumes single Lambda function with exports.handler
var MyLambdaFunction = require('../lambda/index.js'); 

 // this is the Lambda request data, generated by the Alexa service.  Replace with your actual Alexa request.
var event =
{
    "version": "1.0",
    "session": {
        "new": false,
        "sessionId": "amzn1.echo-api.session.f6cdbc9a-df52-4928-911d-cde3304218cb",
        "application": {
            "applicationId": "amzn1.ask.skill.901d1bf9-634e-4702-aec7-cdf5c1f6890c"
        },
        "user": {
            "userId": "amzn1.ask.account.AG5XY76IOLI7NMOZUKIHV5QYF3BTBO64A6BN4OHBQVAVLA3OCSYRLWHD4TLDOONBFDLEGQSVOLSSJM37ANNSMMAALLMUBMQRV7TGZLQ6A7OBR6DVECYJAJZRMPPQHBNGY2KIUN4XOVMO5ZD4CQUHI37RAYPOGX46QTJYVF24PS2DCATV5LRUYCGV7CGVOJXLLIF4R3OKVZK7LBQ"
        },
        "attributes": {}
    },
    "context": {
        "AudioPlayer": {
            "playerActivity": "STOPPED"
        },
        "Display": {},
        "System": {
            "application": {
                "applicationId": "amzn1.ask.skill.35db3565-a832-4d34-b248-0ff545c33bb7"
            },
            "user": {
                "userId": "amzn1.ask.account.AG5XY76IOLI7NMOZUKIHV5QYF3BTBO64A6BN4OHBQVAVLA3OCSYRLWHD4TLDOONBFDLEGQSVOLSSJM37ANNSMMAALLMUBMQRV7TGZLQ6A7OBR6DVECYJAJZRMPPQHBNGY2KIUN4XOVMO5ZD4CQUHI37RAYPOGX46QTJYVF24PS2DCATV5LRUYCGV7CGVOJXLLIF4R3OKVZK7LBQ"
            },
            "device": {
                "deviceId": "amzn1.ask.device.AEEKQMHCF7COPFYPJDTDA5DH7MSE6RCJNHZ4V4VMHZFNN5QHXNVP43KSJSPOBYSJ26FEE7AF6C5PDPD4SX3Y3MGY6EAXKX5ZS5EVES32G663L3HNRFBBBMVLXNWLWAMGQ4HS3566UB2XSSLGEEHTUH4GK4GQ",
                "supportedInterfaces": {
                    "AudioPlayer": {},
                    "Display": {
                        "templateVersion": "1.0",
                        "markupVersion": "1.0"
                    },
                    "VideoApp": {}
                }
            },
            "apiEndpoint": "https://api.eu.amazonalexa.com",
            "apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLjM1ZGIzNTY1LWE4MzItNGQzNC1iMjQ4LTBmZjU0NWMzM2JiNyIsImV4cCI6MTUyMzU0NjU0MSwiaWF0IjoxNTIzNTQyOTQxLCJuYmYiOjE1MjM1NDI5NDEsInByaXZhdGVDbGFpbXMiOnsiY29uc2VudFRva2VuIjpudWxsLCJkZXZpY2VJZCI6ImFtem4xLmFzay5kZXZpY2UuQUVFS1FNSENGN0NPUEZZUEpEVERBNURIN01TRTZSQ0pOSFo0VjRWTUhaRk5ONVFIWE5WUDQzS1NKU1BPQllTSjI2RkVFN0FGNkM1UERQRDRTWDNZM01HWTZFQVhLWDVaUzVFVkVTMzJHNjYzTDNITlJGQkJCTVZMWE5XTFdBTUdRNEhTMzU2NlVCMlhTU0xHRUVIVFVINEdLNEdRIiwidXNlcklkIjoiYW16bjEuYXNrLmFjY291bnQuQUc1WFk3NklPTEk3Tk1PWlVLSUhWNVFZRjNCVEJPNjRBNkJONE9IQlFWQVZMQTNPQ1NZUkxXSEQ0VExET09OQkZETEVHUVNWT0xTU0pNMzdBTk5TTU1BQUxMTVVCTVFSVjdUR1pMUTZBN09CUjZEVkVDWUpBSlpSTVBQUUhCTkdZMktJVU40WE9WTU81WkQ0Q1FVSEkzN1JBWVBPR1g0NlFUSllWRjI0UFMyRENBVFY1TFJVWUNHVjdDR1ZPSlhMTElGNFIzT0tWWks3TEJRIn19.hMgH4G6Zy4KWAttJDbmrQj3DSDWBUeM4BxJwbzh4PvEDAGKtN7tWjsyUVAbvdyUC_5010fZ2LbjhWdvthlcna3vAEiufRpq-cJcs3lvPGIzQjFUv6xBNNzyG2ovT1LTXqZ3yxf4OY_6ogeKcZ6Zv7ybJsbT_gpfRmdX8b35S1taBTKuFR_0oUM9RmT61jXhCkJRaQoeGwSrf-0lkG0gZJTjjEdgy2QoBxZwx7FEgJ9E4Lc7xtEEUE9n7neB6GSzT2LikOa3YeDschL3mA5cxO8BwYPl3NHHOSLcBa3Al5CSgpszDjLdJJA0O3ASnGbfjWH596FUSrS9TwCPuTFqlcQ"
        }
    },
    "request": {
        "type": "IntentRequest",
        "requestId": "amzn1.echo-api.request.2cd48b07-268e-4071-a47a-a05dc790ee48",
        "timestamp": "2018-04-12T15:27:02Z",
        "locale": "en-US",
        "intent": {
            "name": "LaunchRequest",
            "confirmationStatus": "NONE"
        }
    }
};

var context = {
    'succeed': function (data) {
        console.log(JSON.stringify(data, null,'\t') );

    },
    'fail': function (err) {
        console.log('context.fail occurred');
        console.log(JSON.stringify(err, null,'\t') );
    }

};

function callback(error, data) {
    if(error) {
        console.log('error: ' + error);
    } else {
        console.log(data);
    }
}

// call the function
MyLambdaFunction['handler'] (event, context, callback);
